In [9]:
import pandas as pd
import sqlite3

In [7]:
players_batting = pd.read_csv('./Data/players_batting.csv')

In [8]:
players_batting.head()

,player_id,team_id,league_id,position,role,batting_ratings_overall_contact,batting_ratings_overall_gap,batting_ratings_overall_eye,batting_ratings_overall_strikeouts,batting_ratings_overall_hp,...,batting_ratings_talent_gap,batting_ratings_talent_eye,batting_ratings_talent_strikeouts,batting_ratings_talent_hp,batting_ratings_talent_power,batting_ratings_talent_babip,batting_ratings_misc_bunt,batting_ratings_misc_bunt_for_hit,batting_ratings_misc_gb_hitter_type,batting_ratings_misc_fb_hitter_type
0,1,0,0,3,0,22,22,35,33,1,...,22,35,33,1,24,49,61,11,2,2
1,2,42,203,3,0,89,73,130,142,11,...,73,130,142,11,84,92,99,77,1,1
2,3,0,0,6,0,18,11,16,49,7,...,11,16,49,7,3,31,100,84,1,1
3,4,470,209,3,0,56,74,106,54,4,...,77,121,54,4,104,92,113,80,0,0
4,5,0,0,1,11,13,52,14,22,14,...,52,14,22,14,3,45,91,55,1,1